steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [gcloud, functions, deploy, reader, --region=europe-west2, --source=Reader/, --trigger-http, --runtime=nodejs16, --entry-point=read]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [gcloud, functions, deploy, mapper, --region=europe-west2, --source=Mapper/, --trigger-topic=MapperInput, --runtime=nodejs16, --entry-point=mapper]
options:
  logging: CLOUD_LOGGING_ONLY