steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [gcloud, functions, deploy, reader, --region=europe-west2, --source=src/, --trigger-http, --runtime=nodejs16, --entry-point=read]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: [gcloud, functions, deploy, mapper, --region=europe-west2, --source=src/, --trigger-topic=MapperInput, --runtime=nodejs16, --entry-point=map]
options:
  logging: CLOUD_LOGGING_ONLY